version: '2.3'

networks:
  elasticpot_local:

services:

# Elasticpot service
  elasticpot:
    build: .
    container_name: elasticpot
    restart: always
    networks:
     - elasticpot_local
    ports:
     - "9200:9200"
    image: "dtagdevsec/elasticpot:1903"
    read_only: true
    volumes:
     - /data/elasticpot/log:/opt/ElasticpotPY/log
