# This playbook reboots a T-Pot

- hosts: TPOT
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Finally rebooting t-pot in one minute - make sure your next login is on port 64295 or via https:// on port 64297
      shell: /sbin/shutdown -r -t 1
      become: true
